### PR TITLE
parse csv date in ISO format

### PR DESCRIPTION
**Pull request by m11tch**
add support for ISO date format in csv import 
fixes https://github.com/ghostfolio/ghostfolio/issues/1264

### CODE REVIEW

**Comment by m11tch** [comment]
@dtslvr need any input on this?

**Comment by dtslvr** [comment]
Hey @m11tch

> @dtslvr need any input on this?

My comment is still open: I'm not sure if it's a good idea to try parsing the date three times in a row, but I don't know what is more elegant. Any idea?

**Comment by m11tch** [comment]
> Hey @m11tch
> 
> > @dtslvr need any input on this?
> 
> My comment is still open: I'm not sure if it's a good idea to try parsing the date three times in a row, but I don't know what is more elegant. Any idea?

I don't really have a more elegant solution at this time, an alternative could be to only support dates in ISO format as this seems more universal anyway.

**Comment by dtslvr** [comment]
What do you think of my [proposal](https://github.com/ghostfolio/ghostfolio/pull/1303/commits/1fa0c644483fdc47bdecc0fcb717d75e3a3da178) inspired by https://stackoverflow.com/a/67639094/744012 @m11tch?

**Comment by m11tch** [comment]
> What do you think of my [proposal](https://github.com/ghostfolio/ghostfolio/pull/1303/commits/1fa0c644483fdc47bdecc0fcb717d75e3a3da178) inspired by https://stackoverflow.com/a/67639094/744012 @m11tch?

I guess that's cleaner, maybe we could also add if statements for mm-dd-yyyy  and mm/dd/yyyy? (don't have time to test that myself right now) That should cover most import wishes :D

**Review by dtslvr — APPROVED** [review]

**Comment by dtslvr** [comment]
> I guess that's cleaner, maybe we could also add if statements for mm-dd-yyyy and mm/dd/yyyy?

Thanks for the feedback. I think we can add it when it's actually needed.

**Pull request merged**
