### PR TITLE
Feature/switch @typescript-eslint/no-unused-vars to error

### PR DESCRIPTION
**Pull request by dtslvr**

### CODE REVIEW

**Comment by dtslvr** [comment]
cc @dw-0

**Comment by dw-0** [comment]
Do you want to stick to only that eslint rule or do you want to enable `noUnusedLocals` and `noUnusedParameters` from tsconfig.base.json as well? As this will also result in removing unused code.

**Comment by dtslvr** [comment]
* `noUnusedLocals`❓
* `noUnusedParameters` - I think I fixed parameters also in this PR, no?

> As this will also result in removing unused code.
Would you like to tackle this issue on your own or should i also push commits onto this PR?

Feel free 🙂

**Comment by dw-0** [comment]
> * `noUnusedLocals`❓
> * `noUnusedParameters` - I think I fixed parameters also in this PR, no?

https://github.com/dtslvr/ghostfolio/blob/feature/switch-typescript-eslint-no-unused-vars-rule-to-error/tsconfig.base.json#L34-L35
Those two need to be enabled as well. I just saw that i must have f'ed up in the last PR and did not include the TODO above `strict: false`, like we have commented all the other things that are going to be tackled. 😅

> Feel free 🙂

👍

**Pull request merged**
