### PR TITLE
fix: docker compose works against latest docker

### LINKED ISSUE #3745: [Bug] Redis Connection Error
After the latest docker-update (made by watchdog) the landing page can't be reached. 
In Portainer no network and port is bind to the Ghostfolio container.

**To Reproduce**

1. Every time when the landing page is accessed

**Expected behavior**

Landing page opens

**Logs**

Redis Connection Error:  [ErrorReply: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?]
[Nest] 107  - 09/09/2024, 7:27:41 AM   ERROR [ExceptionHandler] ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?

**Environment**

Docker
Self hosted
Debian 12

### PR DESCRIPTION
**Pull request by pazaan**
* Fixes #3745

### CODE REVIEW

**Review by dtslvr — CHANGES_REQUESTED** [review]
Thanks for your contribution, @pazaan.
Could you also adapt [.env.dev](https://github.com/ghostfolio/ghostfolio/blob/main/.env.dev), [docker-compose.build.yml](https://github.com/ghostfolio/ghostfolio/blob/main/docker/docker-compose.build.yml) and [docker-compose.dev.yml](https://github.com/ghostfolio/ghostfolio/blob/main/docker/docker-compose.dev.yml) accordingly?

**Review by dtslvr — CHANGES_REQUESTED** [review]
When I start the development environment, I get the following error:

```
Redis Connection Error:  Error: getaddrinfo ENOTFOUND redis
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
    at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'redis'
}
[Nest] 11428  - 12/11/2024, 8:05:24 PM   ERROR [ExceptionHandler] getaddrinfo ENOTFOUND redis
```

@pazaan any idea what the problem is?

**Comment by pazaan** [comment]
> @pazaan any idea what the problem is?

Apologies - I didn't understand the context for the `docker-compose.dev.yml` file before. After reading `DEVELOPMENT.md` I understand, and have restored `.env.dev` back to what it was before.

**Review by dtslvr — CHANGES_REQUESTED** [review]
Thanks for the recent adaptations, @pazaan!

I attempted to start the development environment again, but encountered this error:
```
Error response from daemon: Conflict. The container name "/gf-postgres" is already in use by container "550c0...". You have to remove (or rename) that container to be able to reuse that name.
```
It's important that the development and production environments can coexist on the same machine without issues.

**Comment by dtslvr** [comment]
> It's important that the development and production environments can coexist on the same machine without issues.

This has been introduced with https://github.com/ghostfolio/ghostfolio/pull/4000.

Maybe it is enough to extend from `docker-compose.yml`, but explicitly set the stack and container names.

**Review by dtslvr — APPROVED** [review]
Thanks for your contribution, @pazaan! `extends` makes the configuration cleaner and easier to maintain. Nice work! 👏🏻

**Pull request merged**
