### PR TITLE
Support arm64

### PR DESCRIPTION
**Pull request by dtslvr**

### CODE REVIEW

**Comment by JDC8077** [comment]
Build failed as per log below:
=================
root@odroid:/media/USBDrive/GhostFolio/ghostfolio# docker-compose -f docker/docker-compose-build-local.yml build
postgres uses an image, skipping
redis uses an image, skipping
Building ghostfolio
Step 1/31 : FROM node:14-alpine as builder
 ---> ff871db46e4f
Step 2/31 : WORKDIR /ghostfolio
 ---> Using cache
 ---> 12708e2c4cbd
Step 3/31 : COPY ./CHANGELOG.md CHANGELOG.md
 ---> 8f39f3e049e4
Step 4/31 : COPY ./LICENSE LICENSE
 ---> 01d0269f1059
Step 5/31 : COPY ./package.json package.json
 ---> 7fa34e5c42e6
Step 6/31 : COPY ./yarn.lock yarn.lock
 ---> fdb83d70f1e7
Step 7/31 : COPY ./prisma/schema.prisma prisma/schema.prisma
 ---> dde0e048861d
Step 8/31 : RUN apk add --no-cache python3 g++ make
 ---> Running in 0cab68586618
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
(1/24) Installing binutils (2.35.2-r2)
(2/24) Installing libgomp (10.3.1_git20210424-r2)
(3/24) Installing libatomic (10.3.1_git20210424-r2)
(4/24) Installing libgphobos (10.3.1_git20210424-r2)
(5/24) Installing gmp (6.2.1-r0)
(6/24) Installing isl22 (0.22-r0)
(7/24) Installing mpfr4 (4.1.0-r0)
(8/24) Installing mpc1 (1.2.1-r0)
(9/24) Installing gcc (10.3.1_git20210424-r2)
(10/24) Installing musl-dev (1.2.2-r3)
(11/24) Installing libc-dev (0.7.2-r3)
(12/24) Installing g++ (10.3.1_git20210424-r2)
(13/24) Installing make (4.3-r0)
(14/24) Installing libbz2 (1.0.8-r1)
(15/24) Installing expat (2.4.1-r0)
(16/24) Installing libffi (3.3-r2)
(17/24) Installing gdbm (1.19-r0)
(18/24) Installing xz-libs (5.2.5-r0)
(19/24) Installing mpdecimal (2.5.1-r1)
(20/24) Installing ncurses-terminfo-base (6.2_p20210612-r0)
(21/24) Installing ncurses-libs (6.2_p20210612-r0)
(22/24) Installing readline (8.1.0-r0)
(23/24) Installing sqlite-libs (3.35.5-r0)
(24/24) Installing python3 (3.9.5-r1)
Executing busybox-1.33.1-r3.trigger
OK: 236 MiB in 40 packages
Removing intermediate container 0cab68586618
 ---> 2ad4dec8d589
Step 9/31 : RUN yarn install
 ---> Running in bcf52d727512
yarn install v1.22.15
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor@4.1.5" has unmet peer dependency "webpack@^4.18.1".
warning " > bootstrap@4.6.0" has unmet peer dependency "jquery@1.9.1 - 3".
warning " > bootstrap@4.6.0" has unmet peer dependency "popper.js@^1.16.1".
warning " > @nrwl/eslint-plugin-nx@12.8.0" has incorrect peer dependency "@typescript-eslint/parser@~4.28.3".
warning " > @storybook/addon-essentials@6.3.8" has unmet peer dependency "@babel/core@^7.9.6".
warning " > @storybook/addon-essentials@6.3.8" has unmet peer dependency "babel-loader@^8.0.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/components@^6.3.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/core-events@^6.3.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/theming@^6.3.0".
warning "@storybook/addon-essentials > @storybook/addons@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addons@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/api@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/api@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > storybook-addon-outline@1.4.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > storybook-addon-outline@1.4.1" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/builder-webpack5 > @storybook/client-api@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/builder-webpack5 > @storybook/client-api@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/builder-webpack5 > @storybook/components@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/builder-webpack5 > @storybook/components@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/builder-webpack5 > @storybook/theming@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/builder-webpack5 > @storybook/theming@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/source-loader@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/source-loader@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > react-element-to-jsx-string@14.3.2" has unmet peer dependency "react@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
warning "@storybook/addon-essentials > @storybook/addon-docs > react-element-to-jsx-string@14.3.2" has unmet peer dependency "react-dom@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
warning "@storybook/builder-webpack5 > @storybook/router@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/builder-webpack5 > @storybook/router@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/api > @reach/router@1.3.4" has unmet peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-essentials > @storybook/api > @reach/router@1.3.4" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > markdown-to-jsx@7.1.3" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-colorful@5.4.0" has unmet peer dependency "react@>=16.8.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-colorful@5.4.0" has unmet peer dependency "react-dom@>=16.8.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react@^16.6.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react-dom@^16.6.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-syntax-highlighter@13.5.3" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-textarea-autosize@8.3.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/theming > @emotion/core@10.1.1" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/theming > @emotion/styled@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/theming > emotion-theming@10.0.27" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/manager-webpack5 > @storybook/ui@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/manager-webpack5 > @storybook/ui@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/manager-webpack5 > @storybook/core-client@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/manager-webpack5 > @storybook/core-client@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-server@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-server@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/api > @reach/router > create-react-context@0.3.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-popper-tooltip > react-popper@2.2.5" has unmet peer dependency "react@^16.8.0 || ^17".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-textarea-autosize > use-composed-ref@1.1.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest@1.2.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/theming > @emotion/styled > @emotion/styled-base@10.0.31" has unmet peer dependency "react@>=16.3.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > downshift@6.1.7" has unmet peer dependency "react@>=16.12.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > markdown-to-jsx@6.11.4" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > react-draggable@4.4.4" has unmet peer dependency "react@>= 16.3.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > react-draggable@4.4.4" has unmet peer dependency "react-dom@>= 16.3.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > react-helmet-async@1.1.2" has unmet peer dependency "react@^16.6.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui > react-helmet-async@1.1.2" has unmet peer dependency "react-dom@^16.6.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-server > @storybook/manager-webpack4@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-server > @storybook/manager-webpack4@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest > use-isomorphic-layout-effect@1.1.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning " > @storybook/angular@6.3.8" has unmet peer dependency "@angular-devkit/architect@>=0.8.9".
warning " > @storybook/angular@6.3.8" has unmet peer dependency "@angular-devkit/core@^0.6.1 || >=7.0.0".
warning " > @storybook/angular@6.3.8" has unmet peer dependency "@babel/core@*".
warning " > @storybook/builder-webpack5@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning " > @storybook/builder-webpack5@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning " > @storybook/manager-webpack5@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning " > @storybook/manager-webpack5@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning " > codelyzer@6.0.1" has incorrect peer dependency "@angular/compiler@>=2.3.1 <12.0.0 || ^11.0.0-next || ^11.1.0-next || ^11.2.0-next".
warning " > codelyzer@6.0.1" has incorrect peer dependency "@angular/core@>=2.3.1 <12.0.0 || ^11.0.0-next || ^11.1.0-next || ^11.2.0-next".
warning " > codelyzer@6.0.1" has unmet peer dependency "tslint@^5.0.0 || ^6.0.0".
[5/5] Building fresh packages...
$ prisma generate && ngcc --properties es2015 browser module main
Error: Unknown binaryTarget linux-arm-openssl-undefined and no custom binaries were provided
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'ghostfolio' failed to build : The command '/bin/sh -c yarn install' returned a non-zero code: 1

**Comment by vzickner** [comment]
HI @JDC8077, hi @dtslvr,

I found those two posts:
https://github.com/prisma/prisma/issues/861#issuecomment-881992292
https://stackoverflow.com/questions/66530969/docker-compose-up-issue-using-docker-apple-m1

Which seems to be the exact same issue. I added `openssl` to the packages, maybe this helps already. Otherwise, we could try to switch from `alpine` to `slim`. However, I am not sure how this is going to affect the size of the docker container.

@JDC8077 can you please re-test? Also, in case it isn't fixed, does it work if you build the docker container on another platform and then execute it on the arm64?

Valentin

**Comment by JDC8077** [comment]
Hi @dtslvr @vzickner 

The build on node:14-apline failed when using your latest Dockerfile changes, failing around the openssl as per attached.
[Log docker arm64 setup- node14-alpine.txt](https://github.com/ghostfolio/ghostfolio/files/7611412/Log.docker.arm64.setup-.node14-alpine.txt)

I took up your suggestion to try on SLIM, chose node:lst-slim. 
- The build was initally NOK, requested to add "linux-arm-openssl-1.1.x" in the schema.prima as binaryTarget, then OK once updated.
-  When up command was launched failed around the PrismaClient as per attached.

[Log docker arm64 setup node-LTS Slim.txt](https://github.com/ghostfolio/ghostfolio/files/7611438/Log.docker.arm64.setup.node-LTS.Slim.txt)

My skills are quite limited at this point, no problem to assist if you have more thoughts.
John

**Comment by vzickner** [comment]
Hi @JDC8077,

did you also change the package to slim around line ~48? It's important that for the build is the same image is used than for the execution.

Valentin

**Comment by JDC8077** [comment]
Hi @vzickner,
Yes, both of the Dockerfile container references where changed. I tried many different arm64 slim containers, the LTS-Slim was the most successful suing the Build command.
John

**Comment by dtslvr** [comment]
I have to merge these changes now. We probably need a new one to solve the original issue.

**Pull request merged**
