### PR TITLE
Add 1w and 1m

### PR DESCRIPTION
**Pull request by amoerie**
As requested in https://github.com/ghostfolio/ghostfolio/discussions/2568 

This PR adds 1W and 1M as possible time intervals when looking at your portfolio.
Please let me know if I missed anything, and thank you for your consideration.

### CODE REVIEW

**Comment by amoerie** [comment]
@dtslvr oh I didn't know someone had already done something similar and that it was rejected. My apologies for the noise.

Are you saying that the WTD and MTD will be included in the work you are already undertaking, and that this PR should simply be closed? In that case, by all means, feel free to reject and remove my work. 👍

**Comment by dtslvr** [comment]
That's no problem.

> Are you saying that the WTD and MTD will be included in the work you are already undertaking

Currently not. If you want to support the ongoing work, you could create a new PR with `WTD` (Monday morning) and `MTD` (start of month) including just `apps/api/src/app/portfolio/portfolio.service.ts` and `apps/api/src/app/user/update-user-setting.dto.ts`.

**Comment by dtslvr** [comment]
> You could create a new PR with `WTD` (Monday morning) and `MTD` (start of month) including just `apps/api/src/app/portfolio/portfolio.service.ts` and `apps/api/src/app/user/update-user-setting.dto.ts`.

I have created an issue for that: https://github.com/ghostfolio/ghostfolio/issues/2900

**Comment by amoerie** [comment]
Looks like @meuter already picked up the linked issue, so I think my work here is done. Thanks, and looking forward to seeing this live on my instance!

**Comment by meuter** [comment]
@amoerie Oh sorry about that. I did not realize there was already a PR about this feature 😨.
Had I know you already worked on this, I would not have proposed to implement it myself.

**Comment by amoerie** [comment]
> @amoerie Oh sorry about that. I did not realize there was already a PR about this feature 😨.
> Had I know you already worked on this, I would not have proposed to implement it myself.

Don't worry about it! I'm already glad it's being worked on, and from a fellow Belgian no less. 😉

**Comment by meuter** [comment]
🇧🇪 🍟 🍺 🍫

**Pull request closed without merging**
