### PR TITLE
Add instructions for API Authorization

### PR DESCRIPTION
**Pull request by dtslvr**

### CODE REVIEW

**Comment by dtslvr** [comment]
What do you think @DerAndereJohannes?

**Review by DerAndereJohannes — APPROVED** [review]
Looks better than what was written before! :-)

**Review by DerAndereJohannes — APPROVED** [review]

**Comment by DerAndereJohannes** [comment]
For future: It might make sense to also create something like API.md (or as part of a wiki) which displays all endpoints and examples how to use them and their outputs.. I can assign myself to this if you know what you prefer more between the two

**Comment by dtslvr** [comment]
> For future: It might make sense to also create something like API.md (or as part of a wiki) which displays all endpoints and examples how to use them and their outputs.. I can assign myself to this if you know what you prefer more between the two

Yes, that makes sense for multiple endpoints. Currently, there is only one public endpoint (import). I'd like to keep it in _README.md_ for simplicity at the moment.

**Comment by DerAndereJohannes** [comment]
> Currently, there is only one public endpoint (import).

Simplicity is always best, I agree. Though, all the endpoints that are available to the webapp are also available to the user through http requests. E.g., using a GET on `http://localhost:3333/api/v2/portfolio/performance?range=1d` along with the authorization header gives you the json output that can be further processed.
```
{
  "chart": [
    {
      "date": "2022-10-31",
      "value": <my hidden result>
    },
    {
      "date": "2022-11-01",
      "value": <my hidden result>
    }
  ],
  "errors": [],
  "hasErrors": false,
  "performance": {
    "currentValue": <my hidden result>,
    "currentGrossPerformance": <my hidden result>,
    "currentGrossPerformancePercent": <my hidden result>,
    "currentNetPerformance": <my hidden result>,
    "currentNetPerformancePercent": <my hidden result>
  }
}
```
Are these stable endpoints?

**Comment by dtslvr** [comment]
That is exactly the point. The (public) API for importing activities is considered to remain stable, all other endpoints are subject to change.

**Comment by DerAndereJohannes** [comment]
Alright, thanks for the clarification! :-)

**Pull request merged**
