### PR TITLE
Upgrade to Nx 17.1

### PR DESCRIPTION
**Pull request by dtslvr**
Running `yarn nx migrate --run-migrations` leads to
```
$ nx migrate --run-migrations
/bin/sh: nx: command not found
```

I have tried to install _Nx_ globally, but when I run the migrations I get an infinite loop of
```
$ nx migrate --run-migrations
$ nx _migrate --run-migrations
$ nx migrate --run-migrations
$ nx _migrate --run-migrations
...
```
Same outcome for running `npx nx migrate --run-migrations`.

### CODE REVIEW

**Comment by dtslvr** [comment]
Running `yarn nx migrate --run-migrations` leads to
```
$ nx migrate --run-migrations
/bin/sh: nx: command not found
```

I have tried to install _Nx_ globally, but when I run the migrations I get an infinite loop of
```
$ nx migrate --run-migrations
$ nx _migrate --run-migrations
$ nx migrate --run-migrations
$ nx _migrate --run-migrations
...
```

**Comment by dtslvr** [comment]
@rahulrk-dev are you able to run migrations?

**Comment by rahulrk-dev** [comment]
> @rahulrk-dev are you able to run migrations?

yes, is it still needed?

**Comment by dtslvr** [comment]
> yes, is it still needed?

Thank you for getting back, @rahulrk-dev!
I have found a workaround in the meantime (see my comment above) ☺️

**Pull request merged**
