### PR TITLE
Fix/@typescript-eslint/consistent-indexed-object-style

### PR DESCRIPTION
**Pull request by dw-0**
depends on #3985 

If you think with this PR there is too much information going to get missing, we have two options i guess:
1. create custom types that better describe what each record holds
2. disable the rule and do not enforce the use of records

### CODE REVIEW

**Comment by dtslvr** [comment]
Yes, I think some of the information is lost. But introducing custom types seems like overkill 🤔

**Comment by dw-0** [comment]
I agree that custom types would be overkill but i don't know how else the "value information" could be preserved. 
The only solution i found so far to keep information from this:
```ts
exchangeRates: { [dateString: string]: number };
```
or this:
```ts
marketSymbolMap: { [date: string]: { [symbol: string]: Big } };
```
is this:
```ts
type DateString = string;
type SymbolString = string;

exchangeRates: Record<DateString, number>;
marketSymbolMap: Record<DateString, Record<SymbolString, Big>>;
```
On the one hand, now it is very clear what the Record is about, on the other hand it feels tedious to go through the project and define dozens of custom types which are only aliases for primitives.

I have no clear opinion on how tragic the lost information is, so that is something you have to decide. 😅

**Comment by dtslvr** [comment]
> On the one hand, now it is very clear what the Record is about, on the other hand it feels tedious to go through the project and define dozens of custom types which are only aliases for primitives.
> 
> I have no clear opinion on how tragic the lost information is, so that is something you have to decide. 😅

Same here. Maybe leave it as it is for now, I don't see the advantage of using `Record`.

**Comment by dw-0** [comment]
Thats fine to me. Any dev who wants to use Record can use it anyways.
Should i create a new PR that switches the rule off? Or would you like to have to shown as a warning still?

**Comment by dtslvr** [comment]
> Should i create a new PR that switches the rule off? Or would you like to have to shown as a warning still?

I’d prefer switching it off. Feel free to go ahead with a PR!

**Pull request closed without merging**
