### PR TITLE
Feature/add support for bonds

### PR DESCRIPTION
**Pull request by dtslvr**

### CODE REVIEW

**Comment by dtslvr** [comment]
Does this categorization (`FIXED_INCOME` > `BOND`) makes sense for you @FedericoComoglio?

**Comment by FedericoComoglio** [comment]
Hi @dtslvr, yes it does. Thank you!

**Comment by BackedUpBooty** [comment]
Hey there, I'm running v 1.150.0.

 I was looking for a specific ISIN (for a Morgan Stanley quarterly note) but it wasn't popping up, looking through the tickets this seemed closest to what I was looking for but I'm not finding where the `FIXED_INCOME` > `BOND` input is meant to be. I can see it as an asset subclass in the schema, but it's not an option when creating an account. Could you point me in the right direction, or if I need to enable it in a particular file?

**Comment by dtslvr** [comment]
Hi @BackedUpBooty

The asset sub class `BOND` is currently only there to assign an asset manually in the database (e.g. for a P2P credit).

If you are able to find your _Morgan Stanley_ quarterly note on [Yahoo Finance](https://finance.yahoo.com) (e.g. via ISIN), there is a chance to support it also in Ghostfolio.

**Comment by BackedUpBooty** [comment]
Ah ok got it. Unfortunately this particular ISIN doesn't seem to be on Yahoo Finance. 

Maybe a suggestion for a future account or gui feature then if possible, add a class for BOND or NOTE that allows us to specify an investment amount, a percentage and a regular payout (monthly/quarterly/annually)? A little more manual than just adding the ISIN, and I can understand why you want to keep everything linked to a symbol or ISIN, but just a thought. 

Thanks!

**Comment by dtslvr** [comment]
Hello @BackedUpBooty

In the _Live Demo_ account on [Ghostfol.io](https://Ghostfol.io) you can see how I'm tracking _Bondora Go & Grow_, a P2P credit.

The unit price is set to 1. The amount is how much you actually have of your bond. Then, the payout is tracked via `DIVIDEND`. Would that also work for your use case?

**Comment by dtslvr** [comment]
Yes, you can add the `DIVIDEND` manually in Ghostfolio.

I would recommend using a tool like [Prisma Studio](https://www.prisma.io/studio) to connect to the database 🙂 Then you can add the (meta) data of your `BOND` in the table `SymbolProfile`.

**Comment by BackedUpBooty** [comment]
So prisma is pretty cool, didn't know about that one, thanks. I successfully spun up a prisma container and connected it to the postgres db, I found the `SymbolProfile` table and added the following:

image

image

However after restarting the postgres, redit and ghostfolio containers, the symbol can't be found. Note that `scraperConfiguration` and `symbolMapping` are set to `_null_` for all the other entries, but Prisma wouldn't let me save this record unless it was set to undefined. Should I be setting it to something else?

**Comment by dtslvr** [comment]
Please use `dataSource`:`GHOSTFOLIO` and `scraperConfiguration`:`{}` / `symbolMapping`:`{}`.
Then you should be able to search for it without restarting the containers.

**Comment by BackedUpBooty** [comment]
Thanks for the pointers, I made those changes but it's still not showing up as an option when I type it into the `Symbol or ISIN` box. I just checked the app logs, and I see this error every now and again:

`[Nest] 1  - 05/25/2022, 12:59:15 AM    WARN [DataGatheringService] Failed to gather data for symbol XS1589841565 from GHOSTFOLIO at 2022-05-24.`

The postgres container is showing 
```2022-05-25 00:59:15.847 UTC [871] ERROR:  duplicate key value violates unique constraint "MarketData_date_symbol_key"
2022-05-25 00:59:15.847 UTC [871] DETAIL:  Key (date, symbol)=(2022-05-23 00:00:00, ZROZ) already exists.
2022-05-25 00:59:15.847 UTC [871] STATEMENT:  INSERT INTO "public"."MarketData" ("createdAt","dataSource","date","id","symbol","marketPrice") VALUES ($1,$2,$3,$4,$5,$6) RETURNING "public"."MarketData"."id"
```
but I can't see any duplication in the table. There's no data in SymbolProfileverrides. I think I saw a similar error on another raised issue but I can't seem to find it to research what a solution may have been.

**Comment by dtslvr** [comment]
> Thanks for the pointers, I made those changes but it's still not showing up as an option when I type it into the `Symbol or ISIN` box.

This is strange. I have just checked it in the cloud and it's working as expected. It's even searching by [name and symbol](https://github.com/ghostfolio/ghostfolio/blob/main/apps/api/src/services/data-provider/ghostfolio-scraper-api/ghostfolio-scraper-api.service.ts#L148) (case insensitive).

> [Nest] 1 - 05/25/2022, 12:59:15 AM WARN [DataGatheringService] Failed to gather data for symbol XS1589841565 from GHOSTFOLIO at 2022-05-24.

These warnings are expected and a consequence of not having a real data provider for your symbol.

**Comment by BackedUpBooty** [comment]
So I tried to set up another symbol, this one is searchable on yahoo finance (https://finance.yahoo.com/quote/DOT-GBP?p=DOT-GBP&.tsrc=fin-srch) but doesn't show up when I search for it in the app to buy or sell. I followed the same instructions as above to add the name 'Polkadot GBP' and the symbol DOTGBP, and although the symbol is definitely filled in, I now get:

```
[Nest] 1  - 05/25/2022, 6:14:37 AM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
[Nest] 1  - 05/25/2022, 6:51:12 AM   ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols
```
I changed the `dataSource` to `GHOSTFOLIO` and recreated the containers to get a fresh log, it's still giving the `ERROR [YahooFinanceService] BadRequestError: Missing required query parameter=symbols` error. 

I'm just going to copy the whole table for you below (sorry it's in two side by side images, i've selected the latest DOT one though so you can see it all the way through). Any suggestions would be great. 

image
image

**Comment by dtslvr** [comment]
I would not recommend to control the software directly with the database.

By the way, _Polkadot_ is available via user interface by default. No need to add it manually.

**Comment by BackedUpBooty** [comment]
> I would not recommend to control the software directly with the database.

Sorry, bit confused, I thought I was following what you were suggesting was necessary if a symbol/product was not already coming up? Do you have any plans to allow for adding of new products from the GUI itself?

> By the way, Polkadot is available via user interface by default. No need to add it manually

Yes but only the DOTUSD pair, I was trying to add the DOTGBP pair.

**Comment by BackedUpBooty** [comment]
Thanks for that. I pulled the new image and confirmed it was the right version (This instance is running Ghostfolio v1.151.0.) and added the env `BASE_CURRENCY=GBP` however the overview does not load, the gui becomes very sluggish, and I get the following errors:

```https://query2.finance.yahoo.com/v7/finance/download/GBPCAD=X?interval=1d&events=history&includeAdjustedClose=true&period1=1652918400&period2=1653523200
[Nest] 1  - 05/26/2022, 8:31:00 AM    WARN [YahooFinanceService] Skipping yahooFinance2.getHistorical("GBPCAD"): [HTTPError] Unauthorized
[Nest] 1  - 05/26/2022, 8:31:00 AM    WARN [DataGatheringService] Failed to gather data for symbol GBPCAD from YAHOO at 2022-05-19.
```
and

```[Nest] 1  - 05/26/2022, 8:31:01 AM   ERROR [GhostfolioScraperApiService] TypeError: aCountries.map is not a function
[Nest] 1  - 05/26/2022, 8:31:03 AM   ERROR [ExchangeRateDataService] No exchange rate has been found for CADUSD
[Nest] 1  - 05/26/2022, 8:35:17 AM    WARN [PortfolioCalculator] Missing initial value for symbol CROUSD at 2021-11-12
[Nest] 1  - 05/26/2022, 8:35:17 AM    WARN [PortfolioCalculator] Missing initial value for symbol DOTUSD at 2021-10-31
[Nest] 1  - 05/26/2022, 8:35:17 AM    WARN [PortfolioCalculator] Missing initial value for symbol ETHUSD at 2021-10-31
```
The admin control page shows this:
image

**Comment by dtslvr** [comment]
> ```
> [Nest] 1  - 05/26/2022, 8:31:00 AM    WARN [YahooFinanceService] Skipping yahooFinance2.getHistorical("GBPCAD"): [HTTPError] Unauthorized
> [Nest] 1  - 05/26/2022, 8:31:00 AM    WARN [DataGatheringService] Failed to gather data for symbol GBPCAD from YAHOO at 2022-05-19.
> ```

Regarding `Unauthorized` and `Unexpected token < in JSON at position 0`: "Yahoo's servers aren't always so reliable, and these occasional errors happen sometimes" according to https://github.com/gadicc/node-yahoo-finance2/issues/349#issuecomment-999360792.

**Comment by BackedUpBooty** [comment]
> "Yahoo's servers aren't always so reliable, and these occasional errors happen sometimes" according to https://github.com/gadicc/node-yahoo-finance2/issues/349#issuecomment-999360792.

OK I can understand that, however this has been a constant error since updating the image and changing the `BASE_CURRENCY` to GBP. Any thoughts on the other errors which I mentioned? 

I also get the following when trying to access the accounts page, portfolio allocations page and portfolio x-ray page

image
image
image

And the following errors in logs:

```Error: [big.js] Invalid number
    at /ghostfolio/apps/api/main.js:1:184637
    at CurrencyClusterRiskBaseCurrencyInitialInvestment.evaluate (/ghostfolio/apps/api/main.js:1:157755)
    at CurrencyClusterRiskBaseCurrencyInitialInvestment.groupCurrentPositionsByAttribute (/ghostfolio/apps/api/main.js:1:152837)
    at Array.map (<anonymous>)
    at /ghostfolio/apps/api/main.js:1:153011
    at Array.reduce (<anonymous>)
    at /ghostfolio/apps/api/main.js:1:153125
    at Big.P.times.P.mul (/ghostfolio/apps/api/node_modules/big.js/big.js:832:17)
    at parse (/ghostfolio/apps/api/node_modules/big.js/big.js:142:13)
    at new Big (/ghostfolio/apps/api/node_modules/big.js/big.js:109:9)
```
```Error: [big.js] Invalid number
    at parse (/ghostfolio/apps/api/node_modules/big.js/big.js:142:13)
    at new Big (/ghostfolio/apps/api/node_modules/big.js/big.js:109:9)
    at Big.P.times.P.mul (/ghostfolio/apps/api/node_modules/big.js/big.js:832:17)
    at PortfolioService.<anonymous> (/ghostfolio/apps/api/main.js:1:193232)
    at Generator.next (<anonymous>)
    at fulfilled (/ghostfolio/apps/api/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

If I remove the `BASE_CURRENCY` variable from the `.env` then I get practically everything back, the accounts and portfolio allocations pages etc. But then the DOTGBP trade I input during when the `BASE_CURRENCY` was changed is showing a log error `[Nest] 1  - 05/27/2022, 1:48:20 AM    WARN [PortfolioCalculator] Missing initial value for symbol DOTGBP at 2022-05-24`. 

It seems that right now, changing the base currency in the .env having already created some trades when it was originally set to default / USD (or back to that default) is causing some issues. I also don't seem to experience the issues communicating with yahoo's servers.

**Comment by BackedUpBooty** [comment]
> You need to wipe the database every time you switch the BASE_CURRENCY. Unfortunately there is no migration path for it.

Ah, OK. That does make it difficult to track if different currencies are used through the trading history, but it's understandable. 

> Historical data is missing sometimes. You can check in your admin panel and complement manually.

Could you explain what you mean by 'complement manually'?

**Comment by dtslvr** [comment]
> Could you explain what you mean by 'complement manually'?

Enter the market values manually in the admin panel 🙂

**Comment by BackedUpBooty** [comment]
Got it, wasn't aware that was an option, found it!

**Pull request merged**
