### PR TITLE
Allow custom currency in activity import

### PR DESCRIPTION
**Pull request by Hugo-Persson**
Issue: https://github.com/ghostfolio/ghostfolio/issues/2187

### CODE REVIEW

**Comment by dtslvr** [comment]
I have made some minor improvements, please check my commits.

**Review by dtslvr — APPROVED** [review]

**Comment by dojoca** [comment]
Hello - hope this is the right place for this. I am trying to import transactions in AUD. I've checked the stock codes are all set up properly (for example, VDHG.AX), but I get an error on import 

> activities.7.currency ("AUD") does not match with "undefined" and no exchange rate is available from "AUD" to "undefined"

Does this mean the issue hasn't been fixed? I'm new to Github so not sure if it means it's been fixed when something has been merged commit?

**Comment by dtslvr** [comment]
> Does this mean the issue hasn't been fixed?

Yes, this has been released in Ghostfolio [1.299.0](https://github.com/ghostfolio/ghostfolio/releases/tag/1.299.0). Which version are you using @dojoca?

**Comment by dojoca** [comment]
I checked the "About" page and it says:
>This instance is running Ghostfolio v1.300.0

Some extra information - 

- I've set my base currency as AUD
- The import is in AUD

This is an extract from the CSV file:

Date,Code,Currency,Price,Quantity,Action,Fee
18/07/2023,VDHG.AX,AUD,0,16,Dividend,0
23/06/2023,VDHG.AX,AUD,57.31,44,Buy,9.5
26/05/2023,WAM.AX,AUD,0,219,Dividend,0
17/05/2023,VDHG.AX,AUD,56.69,74,Buy,9.5
01/05/2023,SMLL.AX,AUD,3.56,959,Buy,9.5
20/04/2023,VDHG.AX,AUD,0,5,Dividend,0
29/03/2023,VDHG.AX,AUD,55.32,86,Buy,9.5
02/03/2023,VDHG.AX,AUD,55.63,59,Buy,9.5
06/02/2023,VDHG.AX,AUD,56.9,53,Buy,9.5
18/01/2023,VDHG.AX,AUD,0,5,Dividend,0
15/12/2022,VDHG.AX,AUD,55.26,64,Buy,9.5

Any ideas what I might be doing wrong?

**Pull request merged**
