### PR TITLE
Feature/support copy assets target on windows

### PR DESCRIPTION
**Pull request by dtslvr**
Error on Windows when running `yarn start:client`:

```
The syntax of the command is incorrect.
cp: cannot overwrite non-directory 'dist/apps/client/assets' with directory 'apps/client/src/assets'
Warning: run-commands command "mkdir -p dist/apps/client" exited with non-zero status codeWarning: run-commands command "cp -r apps/client/src/assets dist/apps/client" exited with non-zero status code
```

### CODE REVIEW

**Comment by dtslvr** [comment]
@FraneCaleta can you please follow these steps and give feedback about the outcome?

1. Check out this branch
1. Run `yarn install`
1. Delete your local `/dist` folder
1. Run `yarn start:client`
1. The `/dist` folder should be created including various assets

**Comment by FraneCaleta** [comment]
Hi @dtslvr,

I've followed your steps exactly as described, but seems like still no luck:
`cp: cannot create directory 'dist/apps/client': No such file or directorycp: cannot create regular file 'dist/apps/client/assets': No such file or directory
cp: cannot create regular file 'dist/apps/client/assets': No such file or directory
cp: cannot create regular file 'dist/apps/client': No such file or directory
cp: cannot create regular file 'dist/apps/client': No such file or directory
cp: cannot create regular file 'dist/apps/client': No such file or directory
cp: cannot create directory 'dist/apps/client': No such file or directory
cp: cannot create regular file 'dist/apps/client': No such file or directory
cp: cannot create directory 'dist/apps/client/ionicons': No such file or directory
cp: cannot create regular file 'dist/apps/client': No such file or directory
cp: cannot overwrite directory 'dist/apps/client' with non-directory
Warning: run-commands command "cross-env cp -r apps/client/src/assets dist/apps/client" exited with non-zero status codeWarning: run-commands command "cross-env cp -r apps/client/src/assets/.well-known dist/apps/client" exited with non-zero status codeWarning: run-commands command "cross-env cp apps/client/src/assets/favicon.ico dist/apps/client" exited with non-zero status codeWarning: run-commands command "cross-env cp apps/client/src/assets/index.html dist/apps/client" exited with non-zero status codeWarning: run-commands command "cross-env cp apps/client/src/assets/robots.txt dist/apps/client" exited with non-zero status codeWarning: run-commands command "cross-env cp apps/client/src/assets/site.webmanifest dist/apps/client" exited with non-zero status codeWarning: run-commands command "cross-env cp node_modules/ionicons/dist/index.js dist/apps/client" exited with non-zero status codeWarning: run-commands command "cross-env cp node_modules/ionicons/dist/ionicons.js dist/apps/client" exited with non-zero status codeWarning: run-commands command "cross-env cp -r node_modules/ionicons/dist/ionicons dist/apps/client/ionicons" exited with non-zero status codeWarning: run-commands command "cross-env cp CHANGELOG.md dist/apps/client/assets" exited with non-zero status codeWarning: run-commands command "cross-env cp LICENSE dist/apps/client/assets" exited with non-zero status code`

Empty directory `./dist/apps/client` got created though.

**Comment by FraneCaleta** [comment]
The procedure works for me with these windows commands instead:
```json 
"commands": [
          {
            "command": "mkdir dist\\apps\\client"
          },
          {
            "command": "xcopy /E /I apps\\client\\src\\assets dist\\apps\\client"
          },
          {
            "command": "xcopy /E /I apps\\client\\src\\assets\\.well-known dist\\apps\\client"
          },
          {
            "command": "copy apps\\client\\src\\assets\\favicon.ico dist\\apps\\client"
          },
          {
            "command": "copy apps\\client\\src\\assets\\index.html dist\\apps\\client"
          },
          {
            "command": "copy apps\\client\\src\\assets\\robots.txt dist\\apps\\client"
          },
          {
            "command": "copy apps\\client\\src\\assets\\site.webmanifest dist\\apps\\client"
          },
          {
            "command": "copy node_modules\\ionicons\\dist\\index.js dist\\apps\\client"
          },
          {
            "command": "copy node_modules\\ionicons\\dist\\ionicons.js dist\\apps\\client"
          },
          {
            "command": "xcopy /E /I /Y node_modules\\ionicons\\dist\\ionicons dist\\apps\\client\\ionicons"
          },
          {
            "command": "copy CHANGELOG.md dist\\apps\\client\\assets"
          },
          {
            "command": "copy LICENSE dist\\apps\\client\\assets"
          }
        ]
```

**Comment by dtslvr** [comment]
> `cp: cannot create directory 'dist/apps/client': No such file or directory`

Strange. It tells that it cannot create the directory, but it's actually there? 🤔

> The procedure works for me with these windows commands

I don't think this works. We need a cross platform solution for Unix and Windows.

**Comment by FraneCaleta** [comment]
> > `cp: cannot create directory 'dist/apps/client': No such file or directory`
> 
> Strange. It tells that it cannot create the directory, but it's actually there? 🤔
> 
Yes, exactly... it's super weird, maybe you could find someone else with Windows system to try it as well?

Even with my Windows specific commands, I'm still missing some of the images for some reason, so it's not a perfect solution either...

**Comment by dtslvr** [comment]
Superseded by #2383.

**Pull request closed without merging**
