### PR TITLE
Feature/introduce admin settings

### PR DESCRIPTION
**Pull request by dtslvr**

### CODE REVIEW

**Comment by dtslvr** [comment]
@FabioAzevedo0619 I have started to restructure the admin control panel. The idea is to introduce a new _Settings_ tab which includes the _Platforms_ and later also the _Tags_ management.

There is an issue I am currently not able to solve: The component `<gf-admin-platform />` is not loaded.

**Comment by FabioAzevedo0619** [comment]
Have you tried adding the exports attribute to the admin-platform.module.ts?

**Comment by dtslvr** [comment]
> Have you tried adding the exports attribute to the admin-platform.module.ts?

Thank you for the hint @FabioAzevedo0619! 😃

**Comment by dtslvr** [comment]
admin-control-settings

I have restructured the admin panel now. @FabioAzevedo0619 you can insert the tags management [here](https://github.com/ghostfolio/ghostfolio/pull/1957/files#diff-7f811dbc2510c7bec6fbd012693fbf895894a8cd2b70f74d81bb16b3c35d5cbdR11) when you start working on it.

**Pull request merged**
